SHELL:=/bin/bash

deployecr:
	$(eval ecr_endpoint:=$(shell aws ecr get-authorization-token | jq -r '.authorizationData[] | .proxyEndpoint' | cut -b 9- ))

	aws ecr get-login-password | docker login --username AWS --password-stdin $(ecr_endpoint)

	docker build --tag app-alpine:latest . --file app/Dockerfile

	docker tag app-alpine:latest $(ecr_endpoint)/app-alpine:latest

	docker push $(ecr_endpoint)/app-alpine:latest

